name: bydoxe_chart
summary: A Flutter Charts library which paint candle chart, depth chart in Exchange Application.
description: A Flutter Charts library which paint candle chart(support select multi secondary state), depth chart in Exchange Application.
version: 1.0.0
homepage: https://github.com/funitlabs/byodxe_chart

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
